// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.0
// source: gorm-db.proto

package gorm

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GORM_PB_TableRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Roleid      int64  `protobuf:"varint,2,opt,name=roleid,proto3" json:"roleid,omitempty"`
	Rolename    string `protobuf:"bytes,3,opt,name=rolename,proto3" json:"rolename,omitempty"`
	Level       int32  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp         int64  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Characterid int32  `protobuf:"varint,6,opt,name=characterid,proto3" json:"characterid,omitempty"`
	Gold        int32  `protobuf:"varint,7,opt,name=gold,proto3" json:"gold,omitempty"`
	Offlinetime int64  `protobuf:"varint,8,opt,name=offlinetime,proto3" json:"offlinetime,omitempty"`
	Inited      int32  `protobuf:"varint,9,opt,name=inited,proto3" json:"inited,omitempty"`
	Createtime  int64  `protobuf:"varint,10,opt,name=createtime,proto3" json:"createtime,omitempty"`
	Face        string `protobuf:"bytes,11,opt,name=face,proto3" json:"face,omitempty"`
	Online      int64  `protobuf:"varint,12,opt,name=online,proto3" json:"online,omitempty"`
	Blob        []byte `protobuf:"bytes,13,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *GORM_PB_TableRole) Reset() {
	*x = GORM_PB_TableRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gorm_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GORM_PB_TableRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GORM_PB_TableRole) ProtoMessage() {}

func (x *GORM_PB_TableRole) ProtoReflect() protoreflect.Message {
	mi := &file_gorm_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GORM_PB_TableRole.ProtoReflect.Descriptor instead.
func (*GORM_PB_TableRole) Descriptor() ([]byte, []int) {
	return file_gorm_db_proto_rawDescGZIP(), []int{0}
}

func (x *GORM_PB_TableRole) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GORM_PB_TableRole) GetRoleid() int64 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

func (x *GORM_PB_TableRole) GetRolename() string {
	if x != nil {
		return x.Rolename
	}
	return ""
}

func (x *GORM_PB_TableRole) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GORM_PB_TableRole) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *GORM_PB_TableRole) GetCharacterid() int32 {
	if x != nil {
		return x.Characterid
	}
	return 0
}

func (x *GORM_PB_TableRole) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GORM_PB_TableRole) GetOfflinetime() int64 {
	if x != nil {
		return x.Offlinetime
	}
	return 0
}

func (x *GORM_PB_TableRole) GetInited() int32 {
	if x != nil {
		return x.Inited
	}
	return 0
}

func (x *GORM_PB_TableRole) GetCreatetime() int64 {
	if x != nil {
		return x.Createtime
	}
	return 0
}

func (x *GORM_PB_TableRole) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

func (x *GORM_PB_TableRole) GetOnline() int64 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *GORM_PB_TableRole) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

var File_gorm_db_proto protoreflect.FileDescriptor

var file_gorm_db_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x6f, 0x72, 0x6d, 0x2d, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x6f, 0x72, 0x6d, 0x22, 0xda, 0x02, 0x0a, 0x12, 0x47, 0x4f, 0x52, 0x4d, 0x5f, 0x50,
	0x42, 0x5f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65,
	0x78, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e,
	0x69, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x6e, 0x69, 0x74,
	0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6c,
	0x6f, 0x62, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x6f, 0x72, 0x6d, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gorm_db_proto_rawDescOnce sync.Once
	file_gorm_db_proto_rawDescData = file_gorm_db_proto_rawDesc
)

func file_gorm_db_proto_rawDescGZIP() []byte {
	file_gorm_db_proto_rawDescOnce.Do(func() {
		file_gorm_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_gorm_db_proto_rawDescData)
	})
	return file_gorm_db_proto_rawDescData
}

var file_gorm_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gorm_db_proto_goTypes = []interface{}{
	(*GORM_PB_TableRole)(nil), // 0: gorm.GORM_PB_Table_role
}
var file_gorm_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gorm_db_proto_init() }
func file_gorm_db_proto_init() {
	if File_gorm_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gorm_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GORM_PB_TableRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gorm_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gorm_db_proto_goTypes,
		DependencyIndexes: file_gorm_db_proto_depIdxs,
		MessageInfos:      file_gorm_db_proto_msgTypes,
	}.Build()
	File_gorm_db_proto = out.File
	file_gorm_db_proto_rawDesc = nil
	file_gorm_db_proto_goTypes = nil
	file_gorm_db_proto_depIdxs = nil
}
