// Generated by gorm.  DO NOT EDIT!

#ifndef _GORM_TABLES_H__
#define _GORM_TABLES_H__

#include "gorm_table_field_map_define.h"
#include "gorm_pb_proto.pb.h"
#include "gorm_table_field_map.h"
#include "gorm_pb_tables_inc.pb.h"
#include "gorm_msg_helper.h"

#include "gorm-db.pb.h"

#endif