// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gorm-db.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gorm_2ddb_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gorm_2ddb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gorm_2ddb_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gorm_2ddb_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gorm_2ddb_2eproto;
namespace gorm {
class GORM_PB_Table_role;
class GORM_PB_Table_roleDefaultTypeInternal;
extern GORM_PB_Table_roleDefaultTypeInternal _GORM_PB_Table_role_default_instance_;
}  // namespace gorm
PROTOBUF_NAMESPACE_OPEN
template<> ::gorm::GORM_PB_Table_role* Arena::CreateMaybeMessage<::gorm::GORM_PB_Table_role>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gorm {

// ===================================================================

class GORM_PB_Table_role PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gorm.GORM_PB_Table_role) */ {
 public:
  inline GORM_PB_Table_role() : GORM_PB_Table_role(nullptr) {};
  virtual ~GORM_PB_Table_role();

  GORM_PB_Table_role(const GORM_PB_Table_role& from);
  GORM_PB_Table_role(GORM_PB_Table_role&& from) noexcept
    : GORM_PB_Table_role() {
    *this = ::std::move(from);
  }

  inline GORM_PB_Table_role& operator=(const GORM_PB_Table_role& from) {
    CopyFrom(from);
    return *this;
  }
  inline GORM_PB_Table_role& operator=(GORM_PB_Table_role&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GORM_PB_Table_role& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GORM_PB_Table_role* internal_default_instance() {
    return reinterpret_cast<const GORM_PB_Table_role*>(
               &_GORM_PB_Table_role_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GORM_PB_Table_role& a, GORM_PB_Table_role& b) {
    a.Swap(&b);
  }
  inline void Swap(GORM_PB_Table_role* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GORM_PB_Table_role* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GORM_PB_Table_role* New() const final {
    return CreateMaybeMessage<GORM_PB_Table_role>(nullptr);
  }

  GORM_PB_Table_role* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GORM_PB_Table_role>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GORM_PB_Table_role& from);
  void MergeFrom(const GORM_PB_Table_role& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GORM_PB_Table_role* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gorm.GORM_PB_Table_role";
  }
  protected:
  explicit GORM_PB_Table_role(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gorm_2ddb_2eproto);
    return ::descriptor_table_gorm_2ddb_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRolenameFieldNumber = 3,
    kFaceFieldNumber = 11,
    kVersionFieldNumber = 1,
    kRoleidFieldNumber = 2,
    kExpFieldNumber = 5,
    kLevelFieldNumber = 4,
    kCharacteridFieldNumber = 6,
    kOfflinetimeFieldNumber = 8,
    kGoldFieldNumber = 7,
    kInitedFieldNumber = 9,
    kCreatetimeFieldNumber = 10,
    kOnlineFieldNumber = 12,
  };
  // string rolename = 3;
  void clear_rolename();
  const std::string& rolename() const;
  void set_rolename(const std::string& value);
  void set_rolename(std::string&& value);
  void set_rolename(const char* value);
  void set_rolename(const char* value, size_t size);
  std::string* mutable_rolename();
  std::string* release_rolename();
  void set_allocated_rolename(std::string* rolename);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_rolename();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_rolename(
      std::string* rolename);
  private:
  const std::string& _internal_rolename() const;
  void _internal_set_rolename(const std::string& value);
  std::string* _internal_mutable_rolename();
  public:

  // string face = 11;
  void clear_face();
  const std::string& face() const;
  void set_face(const std::string& value);
  void set_face(std::string&& value);
  void set_face(const char* value);
  void set_face(const char* value, size_t size);
  std::string* mutable_face();
  std::string* release_face();
  void set_allocated_face(std::string* face);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_face();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_face(
      std::string* face);
  private:
  const std::string& _internal_face() const;
  void _internal_set_face(const std::string& value);
  std::string* _internal_mutable_face();
  public:

  // uint64 version = 1;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::uint64 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_version() const;
  void _internal_set_version(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int64 roleid = 2;
  void clear_roleid();
  ::PROTOBUF_NAMESPACE_ID::int64 roleid() const;
  void set_roleid(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_roleid() const;
  void _internal_set_roleid(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 exp = 5;
  void clear_exp();
  ::PROTOBUF_NAMESPACE_ID::int64 exp() const;
  void set_exp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_exp() const;
  void _internal_set_exp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 level = 4;
  void clear_level();
  ::PROTOBUF_NAMESPACE_ID::int32 level() const;
  void set_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_level() const;
  void _internal_set_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 characterid = 6;
  void clear_characterid();
  ::PROTOBUF_NAMESPACE_ID::int32 characterid() const;
  void set_characterid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_characterid() const;
  void _internal_set_characterid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 offlinetime = 8;
  void clear_offlinetime();
  ::PROTOBUF_NAMESPACE_ID::int64 offlinetime() const;
  void set_offlinetime(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_offlinetime() const;
  void _internal_set_offlinetime(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 gold = 7;
  void clear_gold();
  ::PROTOBUF_NAMESPACE_ID::int32 gold() const;
  void set_gold(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_gold() const;
  void _internal_set_gold(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 inited = 9;
  void clear_inited();
  ::PROTOBUF_NAMESPACE_ID::int32 inited() const;
  void set_inited(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_inited() const;
  void _internal_set_inited(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 createtime = 10;
  void clear_createtime();
  ::PROTOBUF_NAMESPACE_ID::int64 createtime() const;
  void set_createtime(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_createtime() const;
  void _internal_set_createtime(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 online = 12;
  void clear_online();
  ::PROTOBUF_NAMESPACE_ID::int64 online() const;
  void set_online(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_online() const;
  void _internal_set_online(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:gorm.GORM_PB_Table_role)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rolename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr face_;
  ::PROTOBUF_NAMESPACE_ID::uint64 version_;
  ::PROTOBUF_NAMESPACE_ID::int64 roleid_;
  ::PROTOBUF_NAMESPACE_ID::int64 exp_;
  ::PROTOBUF_NAMESPACE_ID::int32 level_;
  ::PROTOBUF_NAMESPACE_ID::int32 characterid_;
  ::PROTOBUF_NAMESPACE_ID::int64 offlinetime_;
  ::PROTOBUF_NAMESPACE_ID::int32 gold_;
  ::PROTOBUF_NAMESPACE_ID::int32 inited_;
  ::PROTOBUF_NAMESPACE_ID::int64 createtime_;
  ::PROTOBUF_NAMESPACE_ID::int64 online_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gorm_2ddb_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GORM_PB_Table_role

// uint64 version = 1;
inline void GORM_PB_Table_role::clear_version() {
  version_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GORM_PB_Table_role::_internal_version() const {
  return version_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GORM_PB_Table_role::version() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.version)
  return _internal_version();
}
inline void GORM_PB_Table_role::_internal_set_version(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  version_ = value;
}
inline void GORM_PB_Table_role::set_version(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.version)
}

// int64 roleid = 2;
inline void GORM_PB_Table_role::clear_roleid() {
  roleid_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::_internal_roleid() const {
  return roleid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::roleid() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.roleid)
  return _internal_roleid();
}
inline void GORM_PB_Table_role::_internal_set_roleid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  roleid_ = value;
}
inline void GORM_PB_Table_role::set_roleid(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.roleid)
}

// string rolename = 3;
inline void GORM_PB_Table_role::clear_rolename() {
  rolename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GORM_PB_Table_role::rolename() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.rolename)
  return _internal_rolename();
}
inline void GORM_PB_Table_role::set_rolename(const std::string& value) {
  _internal_set_rolename(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.rolename)
}
inline std::string* GORM_PB_Table_role::mutable_rolename() {
  // @@protoc_insertion_point(field_mutable:gorm.GORM_PB_Table_role.rolename)
  return _internal_mutable_rolename();
}
inline const std::string& GORM_PB_Table_role::_internal_rolename() const {
  return rolename_.Get();
}
inline void GORM_PB_Table_role::_internal_set_rolename(const std::string& value) {
  
  rolename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GORM_PB_Table_role::set_rolename(std::string&& value) {
  
  rolename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gorm.GORM_PB_Table_role.rolename)
}
inline void GORM_PB_Table_role::set_rolename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  rolename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gorm.GORM_PB_Table_role.rolename)
}
inline void GORM_PB_Table_role::set_rolename(const char* value,
    size_t size) {
  
  rolename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gorm.GORM_PB_Table_role.rolename)
}
inline std::string* GORM_PB_Table_role::_internal_mutable_rolename() {
  
  return rolename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GORM_PB_Table_role::release_rolename() {
  // @@protoc_insertion_point(field_release:gorm.GORM_PB_Table_role.rolename)
  return rolename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GORM_PB_Table_role::set_allocated_rolename(std::string* rolename) {
  if (rolename != nullptr) {
    
  } else {
    
  }
  rolename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rolename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gorm.GORM_PB_Table_role.rolename)
}
inline std::string* GORM_PB_Table_role::unsafe_arena_release_rolename() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gorm.GORM_PB_Table_role.rolename)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return rolename_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GORM_PB_Table_role::unsafe_arena_set_allocated_rolename(
    std::string* rolename) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (rolename != nullptr) {
    
  } else {
    
  }
  rolename_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      rolename, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gorm.GORM_PB_Table_role.rolename)
}

// int32 level = 4;
inline void GORM_PB_Table_role::clear_level() {
  level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::_internal_level() const {
  return level_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::level() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.level)
  return _internal_level();
}
inline void GORM_PB_Table_role::_internal_set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  level_ = value;
}
inline void GORM_PB_Table_role::set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.level)
}

// int64 exp = 5;
inline void GORM_PB_Table_role::clear_exp() {
  exp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::_internal_exp() const {
  return exp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::exp() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.exp)
  return _internal_exp();
}
inline void GORM_PB_Table_role::_internal_set_exp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  exp_ = value;
}
inline void GORM_PB_Table_role::set_exp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.exp)
}

// int32 characterid = 6;
inline void GORM_PB_Table_role::clear_characterid() {
  characterid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::_internal_characterid() const {
  return characterid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::characterid() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.characterid)
  return _internal_characterid();
}
inline void GORM_PB_Table_role::_internal_set_characterid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  characterid_ = value;
}
inline void GORM_PB_Table_role::set_characterid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_characterid(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.characterid)
}

// int32 gold = 7;
inline void GORM_PB_Table_role::clear_gold() {
  gold_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::_internal_gold() const {
  return gold_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::gold() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.gold)
  return _internal_gold();
}
inline void GORM_PB_Table_role::_internal_set_gold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  gold_ = value;
}
inline void GORM_PB_Table_role::set_gold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_gold(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.gold)
}

// int64 offlinetime = 8;
inline void GORM_PB_Table_role::clear_offlinetime() {
  offlinetime_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::_internal_offlinetime() const {
  return offlinetime_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::offlinetime() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.offlinetime)
  return _internal_offlinetime();
}
inline void GORM_PB_Table_role::_internal_set_offlinetime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  offlinetime_ = value;
}
inline void GORM_PB_Table_role::set_offlinetime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_offlinetime(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.offlinetime)
}

// int32 inited = 9;
inline void GORM_PB_Table_role::clear_inited() {
  inited_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::_internal_inited() const {
  return inited_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GORM_PB_Table_role::inited() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.inited)
  return _internal_inited();
}
inline void GORM_PB_Table_role::_internal_set_inited(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  inited_ = value;
}
inline void GORM_PB_Table_role::set_inited(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_inited(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.inited)
}

// int64 createtime = 10;
inline void GORM_PB_Table_role::clear_createtime() {
  createtime_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::_internal_createtime() const {
  return createtime_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::createtime() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.createtime)
  return _internal_createtime();
}
inline void GORM_PB_Table_role::_internal_set_createtime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  createtime_ = value;
}
inline void GORM_PB_Table_role::set_createtime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_createtime(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.createtime)
}

// string face = 11;
inline void GORM_PB_Table_role::clear_face() {
  face_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GORM_PB_Table_role::face() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.face)
  return _internal_face();
}
inline void GORM_PB_Table_role::set_face(const std::string& value) {
  _internal_set_face(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.face)
}
inline std::string* GORM_PB_Table_role::mutable_face() {
  // @@protoc_insertion_point(field_mutable:gorm.GORM_PB_Table_role.face)
  return _internal_mutable_face();
}
inline const std::string& GORM_PB_Table_role::_internal_face() const {
  return face_.Get();
}
inline void GORM_PB_Table_role::_internal_set_face(const std::string& value) {
  
  face_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GORM_PB_Table_role::set_face(std::string&& value) {
  
  face_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gorm.GORM_PB_Table_role.face)
}
inline void GORM_PB_Table_role::set_face(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  face_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gorm.GORM_PB_Table_role.face)
}
inline void GORM_PB_Table_role::set_face(const char* value,
    size_t size) {
  
  face_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gorm.GORM_PB_Table_role.face)
}
inline std::string* GORM_PB_Table_role::_internal_mutable_face() {
  
  return face_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GORM_PB_Table_role::release_face() {
  // @@protoc_insertion_point(field_release:gorm.GORM_PB_Table_role.face)
  return face_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GORM_PB_Table_role::set_allocated_face(std::string* face) {
  if (face != nullptr) {
    
  } else {
    
  }
  face_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), face,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gorm.GORM_PB_Table_role.face)
}
inline std::string* GORM_PB_Table_role::unsafe_arena_release_face() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gorm.GORM_PB_Table_role.face)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return face_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GORM_PB_Table_role::unsafe_arena_set_allocated_face(
    std::string* face) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (face != nullptr) {
    
  } else {
    
  }
  face_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      face, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gorm.GORM_PB_Table_role.face)
}

// int64 online = 12;
inline void GORM_PB_Table_role::clear_online() {
  online_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::_internal_online() const {
  return online_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 GORM_PB_Table_role::online() const {
  // @@protoc_insertion_point(field_get:gorm.GORM_PB_Table_role.online)
  return _internal_online();
}
inline void GORM_PB_Table_role::_internal_set_online(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  online_ = value;
}
inline void GORM_PB_Table_role::set_online(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_online(value);
  // @@protoc_insertion_point(field_set:gorm.GORM_PB_Table_role.online)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace gorm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gorm_2ddb_2eproto
